//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CISM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allowance
    {
        public System.Guid allowance_id { get; set; }
        public System.Guid employee_id { get; set; }
        public int allowance_type_id { get; set; }
        public System.DateTime date { get; set; }
        public decimal amount { get; set; }
        public System.DateTime createddate { get; set; }
        public System.DateTime modifieddate { get; set; }
        public int createduser { get; set; }
        public int modifieduser { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual AllowanceType AllowanceType { get; set; }
    }
}
