//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CISM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusTypeDetailSetting
    {
        public int bonus_setting_dtl_id { get; set; }
        public System.Guid bonus_setting_id { get; set; }
        public int from_year { get; set; }
        public int to_year { get; set; }
        public decimal from_amt { get; set; }
        public decimal to_amt { get; set; }
        public string description { get; set; }
        public System.DateTime createddate { get; set; }
        public System.DateTime modifieddate { get; set; }
        public int createduser { get; set; }
        public int modifieduser { get; set; }
    
        public virtual BonusTypeSetting BonusTypeSetting { get; set; }
    }
}
