//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CISM_PJ.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allowance> Allowances { get; set; }
        public virtual DbSet<AllowanceType> AllowanceTypes { get; set; }
        public virtual DbSet<BonusSetup> BonusSetups { get; set; }
        public virtual DbSet<BonusTypeDetailSetting> BonusTypeDetailSettings { get; set; }
        public virtual DbSet<BonusTypeSetting> BonusTypeSettings { get; set; }
        public virtual DbSet<CitizenShip> CitizenShips { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassByGrade> ClassByGrades { get; set; }
        public virtual DbSet<ClassTimetable> ClassTimetables { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeEducation> EmployeeEducations { get; set; }
        public virtual DbSet<EmployeeFamily> EmployeeFamilies { get; set; }
        public virtual DbSet<EmployeeGrade> EmployeeGrades { get; set; }
        public virtual DbSet<EmployeeHobby> EmployeeHobbies { get; set; }
        public virtual DbSet<EmployeePaymentSetting> EmployeePaymentSettings { get; set; }
        public virtual DbSet<EmployeePersonalSkill> EmployeePersonalSkills { get; set; }
        public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
        public virtual DbSet<EmployeeTypeGrade> EmployeeTypeGrades { get; set; }
        public virtual DbSet<EmploymentHistory> EmploymentHistories { get; set; }
        public virtual DbSet<ExchangeRate> ExchangeRates { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<PaymentMode> PaymentModes { get; set; }
        public virtual DbSet<PeriodSetup> PeriodSetups { get; set; }
        public virtual DbSet<PermissionType> PermissionTypes { get; set; }
        public virtual DbSet<PreviosSchoolRecordByStudent> PreviosSchoolRecordByStudents { get; set; }
        public virtual DbSet<RegNoSetup> RegNoSetups { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<RolePermissionDetail> RolePermissionDetails { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<StaffGrade> StaffGrades { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentGradeHistory> StudentGradeHistories { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<SubjectByGrade> SubjectByGrades { get; set; }
        public virtual DbSet<Timetable> Timetables { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Year> Years { get; set; }
    }
}
