//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CISM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassTimetable
    {
        public System.Guid class_time_table_id { get; set; }
        public System.Guid time_table_id { get; set; }
        public System.Guid subject_id { get; set; }
        public int period_id { get; set; }
        public byte weekday { get; set; }
        public System.DateTime createddate { get; set; }
        public System.DateTime modifieddate { get; set; }
        public int createduser { get; set; }
        public int modifieduser { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual PeriodSetup PeriodSetup { get; set; }
        public virtual SubjectByGrade SubjectByGrade { get; set; }
        public virtual Timetable Timetable { get; set; }
    }
}
