//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CISM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentHistory
    {
        public System.Guid employment_history_id { get; set; }
        public System.Guid employee_id { get; set; }
        public string reg_no { get; set; }
        public System.DateTime year_from { get; set; }
        public System.DateTime year_to { get; set; }
        public string employer { get; set; }
        public string job_title { get; set; }
        public decimal salary { get; set; }
        public System.DateTime createddate { get; set; }
        public System.DateTime modifieddate { get; set; }
        public int createduser { get; set; }
        public int modifieduser { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
