//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CISM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHobby
    {
        public System.Guid hobbies_id { get; set; }
        public System.Guid employee_id { get; set; }
        public string name { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
