//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CISM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreviosSchoolRecordByStudent
    {
        public System.Guid prv_school_id { get; set; }
        public string reg_no { get; set; }
        public System.Guid student_id { get; set; }
        public System.DateTime year_from { get; set; }
        public System.DateTime year_to { get; set; }
        public string passed_grade { get; set; }
        public string attended_school { get; set; }
        public string country { get; set; }
        public System.DateTime createddate { get; set; }
        public System.DateTime modifieddate { get; set; }
        public int createduser { get; set; }
        public int modifieduser { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
