//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CISM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegNoSetup
    {
        public int num_id { get; set; }
        public Nullable<int> format_no { get; set; }
        public string doc_control { get; set; }
        public string doc_prefix { get; set; }
        public string doc_format { get; set; }
        public string next_no { get; set; }
        public string end_no { get; set; }
        public string restart_no { get; set; }
        public System.DateTime createddate { get; set; }
        public System.DateTime modifieddate { get; set; }
        public int createduser { get; set; }
        public int modifieduser { get; set; }
    }
}
