//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CISM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermissionDetail
    {
        public System.Guid rolePermissionDetailId { get; set; }
        public System.Guid rolePermissionId { get; set; }
        public int permissionTypeId { get; set; }
        public System.DateTime createdDate { get; set; }
        public int createdUser { get; set; }
    
        public virtual PermissionType PermissionType { get; set; }
        public virtual RolePermission RolePermission { get; set; }
    }
}
