//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CISM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RolePermission()
        {
            this.RolePermissionDetails = new HashSet<RolePermissionDetail>();
        }
    
        public System.Guid rolePermissionId { get; set; }
        public System.Guid roleId { get; set; }
        public short menuID { get; set; }
        public System.DateTime createdDate { get; set; }
        public int createdUser { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolePermissionDetail> RolePermissionDetails { get; set; }
    }
}
