//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CISM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public System.Guid school_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> established_year { get; set; }
        public string head_master_name { get; set; }
        public string addres { get; set; }
        public string ph_code { get; set; }
        public string ph_office { get; set; }
        public string email { get; set; }
        public Nullable<int> currency_id { get; set; }
        public string country { get; set; }
        public System.DateTime createddate { get; set; }
        public System.DateTime modifieddate { get; set; }
        public int createduser { get; set; }
        public int modifieduser { get; set; }
    
        public virtual Currency Currency { get; set; }
    }
}
